-- MySQL Script generated by MySQL Workbench
-- Mon Oct 20 21:04:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema level1ex2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `level1ex2` ;

-- -----------------------------------------------------
-- Schema level1ex2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `level1ex2` DEFAULT CHARACTER SET utf8 ;
USE `level1ex2` ;

-- -----------------------------------------------------
-- Table `level1ex2`.`province`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`province` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`province` (
  `province_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`province_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `level1ex2`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`city` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`city` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`city_id`),
  CONSTRAINT `city_province`
    FOREIGN KEY (`province_id`)
    REFERENCES `level1ex2`.`province` (`province_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `city_province_idx` ON `level1ex2`.`city` (`province_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `level1ex2`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`customer` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `city_id` INT NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id`),
  CONSTRAINT `customer_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `level1ex2`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `customer_city_idx` ON `level1ex2`.`customer` (`city_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `level1ex2`.`shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`shop` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`shop` (
  `shop_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`shop_id`),
  CONSTRAINT `shop_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `level1ex2`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `shop_city_idx` ON `level1ex2`.`shop` (`city_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `level1ex2`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`employee` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `position` ENUM('cook', 'deliverer') NOT NULL,
  `shop_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  CONSTRAINT `employee_shop`
    FOREIGN KEY (`shop_id`)
    REFERENCES `level1ex2`.`shop` (`shop_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `employee_shop_idx` ON `level1ex2`.`employee` (`shop_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `nif_UNIQUE` ON `level1ex2`.`employee` (`nif` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `level1ex2`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`order` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `type` ENUM('delivery', 'shop') NOT NULL,
  `total_price` FLOAT NOT NULL,
  `customer_id` INT NOT NULL,
  `shop_id` INT NOT NULL,
  `deliverer_id` INT NULL,
  `delivery_date` DATETIME NULL,
  PRIMARY KEY (`order_id`),
  CONSTRAINT `order_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `level1ex2`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_shop`
    FOREIGN KEY (`shop_id`)
    REFERENCES `level1ex2`.`shop` (`shop_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_deliverer`
    FOREIGN KEY (`deliverer_id`)
    REFERENCES `level1ex2`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `customer_id_idx` ON `level1ex2`.`order` (`customer_id` ASC) VISIBLE;

CREATE INDEX `order_shop_idx` ON `level1ex2`.`order` (`shop_id` ASC) VISIBLE;

CREATE INDEX `order_deliverer_idx` ON `level1ex2`.`order` (`deliverer_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `level1ex2`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`product` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('pizza', 'burger', 'drink') NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `level1ex2`.`order_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`order_product` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`order_product` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  CONSTRAINT `order_product_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `level1ex2`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_product_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `level1ex2`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `order_idx` ON `level1ex2`.`order_product` (`order_id` ASC) VISIBLE;

CREATE INDEX `product_idx` ON `level1ex2`.`order_product` (`product_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `level1ex2`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`category` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `level1ex2`.`pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`pizza` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`pizza` (
  `pizza_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`pizza_id`),
  CONSTRAINT `pizza_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `level1ex2`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pizza_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `level1ex2`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `pizza_category_idx` ON `level1ex2`.`pizza` (`category_id` ASC) VISIBLE;

CREATE INDEX `fk_pizza_product1_idx` ON `level1ex2`.`pizza` (`product_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
