-- MySQL Script generated by MySQL Workbench
-- Tue Oct 21 18:49:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema level1ex2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `level1ex2` ;

-- -----------------------------------------------------
-- Schema level1ex2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `level1ex2` DEFAULT CHARACTER SET utf8 ;
USE `level1ex2` ;

-- -----------------------------------------------------
-- Table `level1ex2`.`provinces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`provinces` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`provinces` (
  `province_id` INT NOT NULL AUTO_INCREMENT,
  `province_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`province_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `level1ex2`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`cities` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`cities` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(45) NOT NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`city_id`),
  CONSTRAINT `city_province`
    FOREIGN KEY (`province_id`)
    REFERENCES `level1ex2`.`provinces` (`province_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `city_province_idx` ON `level1ex2`.`cities` (`province_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `level1ex2`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`customers` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `city_id` INT NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id`),
  CONSTRAINT `customer_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `level1ex2`.`cities` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `customer_city_idx` ON `level1ex2`.`customers` (`city_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `level1ex2`.`shops`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`shops` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`shops` (
  `shop_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`shop_id`),
  CONSTRAINT `shop_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `level1ex2`.`cities` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `shop_city_idx` ON `level1ex2`.`shops` (`city_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `level1ex2`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`employees` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`employees` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `employee_name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `position` ENUM('cook', 'deliverer') NOT NULL,
  `shop_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  CONSTRAINT `employee_shop`
    FOREIGN KEY (`shop_id`)
    REFERENCES `level1ex2`.`shops` (`shop_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `employee_shop_idx` ON `level1ex2`.`employees` (`shop_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `nif_UNIQUE` ON `level1ex2`.`employees` (`nif` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `level1ex2`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`orders` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `order_date` DATETIME NOT NULL,
  `type` ENUM('delivery', 'shop') NOT NULL,
  `total_price` FLOAT NOT NULL,
  `customer_id` INT NOT NULL,
  `shop_id` INT NOT NULL,
  `deliverer_id` INT NULL,
  `delivery_date` DATETIME NULL,
  PRIMARY KEY (`order_id`),
  CONSTRAINT `order_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `level1ex2`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_shop`
    FOREIGN KEY (`shop_id`)
    REFERENCES `level1ex2`.`shops` (`shop_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_deliverer`
    FOREIGN KEY (`deliverer_id`)
    REFERENCES `level1ex2`.`employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `customer_id_idx` ON `level1ex2`.`orders` (`customer_id` ASC) VISIBLE;

CREATE INDEX `order_shop_idx` ON `level1ex2`.`orders` (`shop_id` ASC) VISIBLE;

CREATE INDEX `order_deliverer_idx` ON `level1ex2`.`orders` (`deliverer_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `level1ex2`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`products` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_type` ENUM('pizza', 'burger', 'drink') NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `level1ex2`.`orders_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`orders_products` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`orders_products` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `amount` INT NOT NULL,
  CONSTRAINT `order_product_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `level1ex2`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_product_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `level1ex2`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `order_idx` ON `level1ex2`.`orders_products` (`order_id` ASC) VISIBLE;

CREATE INDEX `product_idx` ON `level1ex2`.`orders_products` (`product_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `level1ex2`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`categories` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `level1ex2`.`pizzas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex2`.`pizzas` ;

CREATE TABLE IF NOT EXISTS `level1ex2`.`pizzas` (
  `pizza_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`pizza_id`),
  CONSTRAINT `pizza_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `level1ex2`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pizza_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `level1ex2`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `pizza_category_idx` ON `level1ex2`.`pizzas` (`category_id` ASC) VISIBLE;

CREATE INDEX `fk_pizza_product1_idx` ON `level1ex2`.`pizzas` (`product_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
