-- MySQL Script generated by MySQL Workbench
-- Mon Oct 20 20:57:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema level1ex1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `level1ex1` ;

-- -----------------------------------------------------
-- Schema level1ex1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `level1ex1` DEFAULT CHARACTER SET utf8 ;
USE `level1ex1` ;

-- -----------------------------------------------------
-- Table `level1ex1`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex1`.`address` ;

CREATE TABLE IF NOT EXISTS `level1ex1`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `floor` VARCHAR(45) NULL,
  `door` VARCHAR(45) NULL,
  `city` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `level1ex1`.`provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex1`.`provider` ;

CREATE TABLE IF NOT EXISTS `level1ex1`.`provider` (
  `provider_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address_id` INT NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `fax` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`provider_id`),
  CONSTRAINT `provider_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `level1ex1`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nif_UNIQUE` ON `level1ex1`.`provider` (`nif` ASC) VISIBLE;

CREATE INDEX `provider_address_idx` ON `level1ex1`.`provider` (`address_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `level1ex1`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex1`.`brand` ;

CREATE TABLE IF NOT EXISTS `level1ex1`.`brand` (
  `brand_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `provider_id` INT NOT NULL,
  PRIMARY KEY (`brand_id`),
  CONSTRAINT `brand_provider`
    FOREIGN KEY (`provider_id`)
    REFERENCES `level1ex1`.`provider` (`provider_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `brand_provider_idx` ON `level1ex1`.`brand` (`provider_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `level1ex1`.`glasses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex1`.`glasses` ;

CREATE TABLE IF NOT EXISTS `level1ex1`.`glasses` (
  `glasses_id` INT NOT NULL AUTO_INCREMENT,
  `lens_prescription_left` FLOAT NOT NULL,
  `lens_prescription_right` FLOAT NOT NULL,
  `frame_type` ENUM('rimless', 'plastic', 'metal') NOT NULL,
  `frame_color` VARCHAR(45) NOT NULL,
  `lens_color_left` VARCHAR(45) NOT NULL,
  `lens_color_right` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `brand_id` INT NOT NULL,
  PRIMARY KEY (`glasses_id`),
  CONSTRAINT `glasses_brand`
    FOREIGN KEY (`brand_id`)
    REFERENCES `level1ex1`.`brand` (`brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `glasses_brand_idx` ON `level1ex1`.`glasses` (`brand_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `level1ex1`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex1`.`customer` ;

CREATE TABLE IF NOT EXISTS `level1ex1`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address_id` INT NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `registration_date` DATE NOT NULL,
  `recommender_id` INT NULL,
  PRIMARY KEY (`customer_id`),
  CONSTRAINT `customer_recommender`
    FOREIGN KEY (`recommender_id`)
    REFERENCES `level1ex1`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `level1ex1`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `recommender_idx` ON `level1ex1`.`customer` (`recommender_id` ASC) VISIBLE;

CREATE INDEX `customer_address_idx` ON `level1ex1`.`customer` (`address_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `level1ex1`.`seller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex1`.`seller` ;

CREATE TABLE IF NOT EXISTS `level1ex1`.`seller` (
  `seller_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`seller_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `level1ex1`.`sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level1ex1`.`sale` ;

CREATE TABLE IF NOT EXISTS `level1ex1`.`sale` (
  `sale_id` INT NOT NULL AUTO_INCREMENT,
  `seller_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `glasses_id` INT NOT NULL,
  PRIMARY KEY (`sale_id`),
  CONSTRAINT `sale_seller`
    FOREIGN KEY (`seller_id`)
    REFERENCES `level1ex1`.`seller` (`seller_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sale_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `level1ex1`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sale_glasses`
    FOREIGN KEY (`glasses_id`)
    REFERENCES `level1ex1`.`glasses` (`glasses_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `seller_idx` ON `level1ex1`.`sale` (`seller_id` ASC) VISIBLE;

CREATE INDEX `glasses_idx` ON `level1ex1`.`sale` (`glasses_id` ASC) VISIBLE;

CREATE INDEX `customer_idx` ON `level1ex1`.`sale` (`customer_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
